import PDFDocument from 'pdfkit';
import fs from 'fs';
import path from 'path';
import { uploadPDFToCloudinary } from './cloudinaryService.js';

// Generate PDF from structured notes
export const generatePDF = async (structuredNotes, originalFilename = 'audio') => {
  try {
    console.log('Starting PDF generation...');

    // Create PDFs directory if it doesn't exist
    const pdfsDir = './uploads/pdfs';
    if (!fs.existsSync(pdfsDir)) {
      fs.mkdirSync(pdfsDir, { recursive: true });
    }

    // Generate unique PDF filename
    const timestamp = Date.now();
    const pdfFilename = `${timestamp}-${originalFilename}-notes.pdf`;
    const pdfPath = path.join(pdfsDir, pdfFilename);

    // Create PDF document
    const doc = new PDFDocument({
      margin: 50,
      size: 'A4'
    });

    // Pipe PDF to file
    doc.pipe(fs.createWriteStream(pdfPath));

    // Add header
    doc.fontSize(20)
       .font('Helvetica-Bold')
       .text('AI Generated Notes', { align: 'center' })
       .moveDown();

    doc.fontSize(12)
       .font('Helvetica')
       .text(`Generated on: ${new Date().toLocaleDateString()}`, { align: 'center' })
       .text(`Source: ${originalFilename}`, { align: 'center' })
       .moveDown(2);

    // Process and add structured notes
    const lines = structuredNotes.split('\n');
    
    for (const line of lines) {
      if (line.trim() === '') {
        doc.moveDown(0.5);
        continue;
      }

      // Handle different markdown elements
      if (line.startsWith('# ')) {
        // Main heading
        doc.fontSize(18)
           .font('Helvetica-Bold')
           .text(line.substring(2), { align: 'left' })
           .moveDown();
      } else if (line.startsWith('## ')) {
        // Sub heading
        doc.fontSize(14)
           .font('Helvetica-Bold')
           .text(line.substring(3), { align: 'left' })
           .moveDown(0.5);
      } else if (line.startsWith('### ')) {
        // Sub-sub heading
        doc.fontSize(12)
           .font('Helvetica-Bold')
           .text(line.substring(4), { align: 'left' })
           .moveDown(0.3);
      } else if (line.startsWith('- ')) {
        // Bullet point
        doc.fontSize(11)
           .font('Helvetica')
           .text('• ' + line.substring(2), { 
             indent: 20,
             align: 'left'
           })
           .moveDown(0.2);
      } else if (line.startsWith('**') && line.endsWith('**')) {
        // Bold text
        doc.fontSize(11)
           .font('Helvetica-Bold')
           .text(line.substring(2, line.length - 2), { align: 'left' })
           .moveDown(0.3);
      } else {
        // Regular text
        doc.fontSize(11)
           .font('Helvetica')
           .text(line, { align: 'left' })
           .moveDown(0.3);
      }
    }

    // Add footer
    doc.fontSize(8)
       .font('Helvetica')
       .text('Generated by AI Notes System', 50, doc.page.height - 50, {
         align: 'center'
       });

    // Finalize PDF
    doc.end();

    // Wait for PDF to be written to disk
    await new Promise((resolve) => {
      doc.on('end', resolve);
    });

    console.log('PDF generation completed:', pdfPath);

    // Upload PDF to Cloudinary
    const cloudinaryResult = await uploadPDFToCloudinary(pdfPath, originalFilename);

    return {
      pdfPath: pdfPath,
      pdfFilename: pdfFilename,
      cloudinaryUrl: cloudinaryResult.url,
      cloudinaryPublicId: cloudinaryResult.publicId,
      size: cloudinaryResult.size,
      generatedAt: new Date()
    };

  } catch (error) {
    console.error('PDF generation error:', error);
    throw new Error('Failed to generate PDF: ' + error.message);
  }
};